name: ESMplot_py3.10
channels:
  - defaults
  - conda-forge
  - ncar         
dependencies:
  - python=3.10
  - numpy=1.23.5
  - geocat-f2py=2022.04.0
  - cartopy=0.21.1
  - cmaps=1.0.5
  - geocat-comp=2022.8.0
  - geocat-viz=2022.7.0
  - icecream=2.1.3
  - openpyxl=3.0.10
  - pint=0.19.2
  - xskillscore=0.0.24
prefix: /RAID/home/ajthompson/anaconda3/envs/ESMplot_py3.10
